name: Build Dist

on:
  push:
    pull_request:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  distcheck:
    name: Dist check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup the container
      uses: canonical/desktop-engineering/gh-actions/common/dpkg-install-speedup@main

    - name: Install dependencies
      run: |
        sudo npm install eslint@8.57.0 -g
        sudo apt install -y \
          jq \
          gettext \
          meson \
          zip

    - name: Dist check extension
      run: |
        meson setup _build
        meson test -C _build -v --print-errorlogs
        ninja -C _build zip-file
